agent/pom.xml
agent/src/main/java/org/jboss/byteman/agent/Location.java
agent/src/main/java/org/jboss/byteman/agent/LocationType.java
agent/src/main/java/org/jboss/byteman/agent/adapter/ExceptionExitCheckAdapter.java
agent/src/main/java/org/jboss/byteman/agent/adapter/ExceptionExitTriggerAdapter.java
agent/src/test/java/org/jboss/byteman/tests/auxiliary/TestExceptionExitAuxiliary.java
agent/src/test/java/org/jboss/byteman/tests/location/TestExceptionExit.java
agent/src/test/resources/scripts/location/TestExceptionExit.btm

*NOT* intended to be merged yet, but just for review to discover issues with the approach and what else may need to be done.

Add support for exceptional exit

---

docs/asciidoc/pom.xml
docs/asciidoc/src/main/asciidoc/byteman-programmers-guide.adoc
docs/asciidoc/src/main/asciidoc/chapters/Byteman-Rule-Language-Standard-Built-Ins.adoc
docs/asciidoc/src/main/asciidoc/chapters/Byteman-Rule-Language.adoc
docs/asciidoc/src/main/asciidoc/chapters/Introduction.adoc
docs/asciidoc/src/main/asciidoc/chapters/Using-Byteman.adoc
docs/pom.xml

See https://issues.jboss.org/browse/BYTEMAN-300
Converts the current open-office based documentation into asciidoc. 
There was a minor modification to the docs in the 3.0.2 releaes, I think? I'm not 100% sure that I incorporated that in the asiidoc based docs.

BYTEMAN-300 - Convert documentation to AsciiDoc

---

README

Cleaned up a couple of typos in the readme

fixed spelling mistakes in the readme

---

contrib/jboss-modules-system/plugin/src/main/java/org/jboss/byteman/modules/jbossmodules/JBossModulesSystem.java
contrib/rulecheck-maven-plugin/pom.xml
docs/pom.xml
pom.xml

Hi,
I've found various issues which will prevent you from doing a successful release.
I suspect the build was working fine for you as you had an old copy of the documentation already in the local build tree, but it failed for me as I was doing a clean build; it might have released stale copies of the docs.
HTH

Resolving various build issues

---

agent/src/main/java/org/jboss/byteman/agent/TransformListener.java

Signed-off-by: Han Qiao <qh812@imperial.ac.uk>

always close socket after agent listener replies

---

contrib/dtest/src/main/java/org/jboss/byteman/contrib/dtest/InstrumentedInstance.java
contrib/dtest/src/main/java/org/jboss/byteman/contrib/dtest/Instrumentor.java

https://issues.jboss.org/browse/BYTEMAN-345
https://github.com/bytemanproject/byteman/pull/63

[BYTEMAN-345] dtest instrument instance concurrency fail 4.0.0.beta

---

.gitignore
sample/src/org/jboss/byteman/sample/helper/ThreadHistoryMonitorHelper.java

https://issues.jboss.org/browse/BYTEMAN-351

[BYTEMAN-351] Shutdown scheduled executor from sample thread helper class

---

bin/bmcheck.sh
bin/bminstall.sh
bin/bmjava.sh
bin/bmsubmit.sh
bin/bytemancheck.sh

to not failing when path contains a space character
https://issues.jboss.org/browse/BYTEMAN-352

[BYTEMAN-352] shell script tools to wrap paths with quotes

---

contrib/dtest/src/main/java/org/jboss/byteman/contrib/dtest/BytemanTestHelper.java
contrib/dtest/src/main/java/org/jboss/byteman/contrib/dtest/Instrumentor.java
contrib/dtest/src/main/java/org/jboss/byteman/contrib/dtest/RuleConstructor.java
contrib/dtest/src/test/java/org/jboss/byteman/contrib/dtest/InstrumentorTest.java
contrib/dtest/src/test/java/org/jboss/byteman/contrib/dtest/RuleConstructorTestCase.java

https://issues.jboss.org/browse/BYTEMAN-353

[BYTEMAN-353] Dtest enhancements of rule constructor and defaulting rmi port

---

agent/src/main/java/org/jboss/byteman/agent/Main.java

@adinn : only a cosmetic enhancement

enhancing error message when wrong agent argument is used

---

pom.xml

https://issues.jboss.org/browse/BYTEMAN-378

[BYTEMAN-378] Upgrade ASM to 7.1 to bring in JDK 13 support.

---

contrib/bmunit5/src/main/java/org/jboss/byteman/contrib/bmunit/BMUnit5AbstractHandler.java
contrib/bmunit5/src/main/java/org/jboss/byteman/contrib/bmunit/BMUnit5ConfigHandler.java

fixing issue, https://issues.jboss.org/browse/BYTEMAN-382,

using isPresent so we can use Byteman in JDK 8, 9, and 10

---

agent/src/main/java/org/jboss/byteman/rule/helper/Helper.java

Some minor tuning for contention on Helper#traceMap

Tracing made a little more scalable

---

docs/asciidoc/pom.xml
pom.xml

https://issues.redhat.com/browse/BYTEMAN-411 Upgrade JRUBY to 9.2.17.0
https://issues.redhat.com/browse/BYTEMAN-412 Upgrade ASM to 9.1

Component Upgrades

---

README
agent/noverification.xml
agent/pom.xml
pom.xml
tests/noverification.xml
tests/pom.xml

https://issues.redhat.com/browse/BYTEMAN-414

[BYTEMAN-414] speed up compilation to skip tests and doc generation

---

sample/scripts/ThreadMonitorHistory.btm
sample/src/org/jboss/byteman/sample/helper/ThreadHistoryMonitorHelper.java
sample/src/org/jboss/byteman/sample/helper/ThreadMonitorEventType.java
sample/src/org/jboss/byteman/sample/helper/ThreadMonitored.java

plus enhancing the structure with Callable handling
https://issues.redhat.com/browse/BYTEMAN-415

[BYTEMAN-415] removing recursive structure for thread history helper MXBean to work in JDK11

---

pom.xml

https://issues.redhat.com/browse/BYTEMAN-419 JDK 18 support

[BYTEMAN-419] Upgrade ASM to 9.2

---

pom.xml

https://issues.redhat.com/browse/BYTEMAN-422

[BYTEMAN-422] Upgrade ASM to 9.3

---

pom.xml

https://issues.redhat.com/browse/BYTEMAN-426

[BYTEMAN-426] Upgrade ASM to 9.4

---

pom.xml

https://issues.redhat.com/browse/BYTEMAN-429

[BYTEMAN-429] Upgrade ASM to 9.5

---

pom.xml

https://issues.redhat.com/browse/BYTEMAN-436

[BYTEMAN-436] Upgrade ASM to 9.6

---

agent/pom.xml
agent/src/main/java/org/jboss/byteman/agent/Main.java
agent/src/test/java/org/jboss/byteman/tests/jar/TestScriptFromJar.java
agent/src/test/resources/scripts/jar/TestScriptFromJar.btm

https://issues.redhat.com/projects/BYTEMAN/issues/BYTEMAN-437

Proposed support for reading .btm scripts from a jar URL

---

pom.xml

https://issues.redhat.com/browse/BYTEMAN-439

[BYTEMAN-439] Upgrade ASM to 9.7

---

pom.xml

https://issues.redhat.com/browse/BYTEMAN-444

[BYTEMAN-444] Upgrade ASM to 9.8
